### ISSUE TITLE
MV3 reinjects on service worker restart

### ISSUE THREAD

**Issue by twschiller** [bfred-it/webext-inject-on-install#7]
- In this branch: https://github.com/pixiebrix/pixiebrix-extension/pull/7232, was seeing console logging indicating webext-inject-on-install is running multiple times
- Does it need to check for https://developer.chrome.com/docs/extensions/reference/api/runtime#event-onStartup or similar?

**Comment by fregante** [comment]
onStartup refers to the browser startup, not the extension.

onInstalled covers the common scenario, but it won't work if they user re-enables a disabled extension, or if you reload it during development.

I recently created an event for this, based on `chrome.session`, I'll try using it here: https://github.com/fregante/webext-events/blob/main/source/on-extension-start.md

It seems that soon they'll work on the `onEnabled` event, which is the right API for us:

- https://github.com/fregante/webext-events/issues/16

**Comment by twschiller** [comment]
At least in our project, it's not a high priority as we guard against re-injection. I just wanted to capture the issue as something to be aware of (and could impact other users of this library)
